# !/bin/bash

./siguel -f c1.geo -o /home/juomzin/Documentos/saidas -e /home/juomzin/Documentos/testes/c1 -q c1/1000-dados-estabelecimentos.qry -pm c1.pm -ec c1.ec
./siguel -f c1.geo -o /home/juomzin/Documentos/saidas -e /home/juomzin/Documentos/testes/c1 -q c1/1000-dados-morador -pm c1.pm -ec c1.ec
./siguel -f c1.geo -o /home/juomzin/Documentos/saidas -e /home/juomzin/Documentos/testes/c1 -q c1/1000-mudanca-morador -pm c1.pm -ec c1.ec
./siguel -f c1.geo -o /home/juomzin/Documentos/saidas -e /home/juomzin/Documentos/testes/c1 -q c1/catac-centrosul-cidade-amplo.qry -pm c1.pm -ec c1.ec
./siguel -f c1.geo -o /home/juomzin/Documentos/saidas -e /home/juomzin/Documentos/testes/c1 -q c1/catac-dump-1.qry -pm c1.pm -ec c1.ec
./siguel -f c1.geo -o /home/juomzin/Documentos/saidas -e /home/juomzin/Documentos/testes/c1 -q c1/catac-dump-2.qry -pm c1.pm -ec c1.ec
./siguel -f c1.geo -o /home/juomzin/Documentos/saidas -e /home/juomzin/Documentos/testes/c1 -q c1/catac-dump-3.qry -pm c1.pm -ec c1.ec
./siguel -f c1.geo -o /home/juomzin/Documentos/saidas -e /home/juomzin/Documentos/testes/c1 -q c1/catac-dump-4.qry -pm c1.pm -ec c1.ec
./siguel -f c1.geo -o /home/juomzin/Documentos/saidas -e /home/juomzin/Documentos/testes/c1 -q c1/catac-meio-cidade-amplo.qry -pm c1.pm -ec c1.ec
./siguel -f c1.geo -o /home/juomzin/Documentos/saidas -e /home/juomzin/Documentos/testes/c1 -q c1/catac-meio-muito-estreito.qry -pm c1.pm -ec c1.ec
./siguel -f c1.geo -o /home/juomzin/Documentos/saidas -e /home/juomzin/Documentos/testes/c1 -q c1/classe-2000.qry -pm c1.pm -ec c1.ec
./siguel -f c1.geo -o /home/juomzin/Documentos/saidas -e /home/juomzin/Documentos/testes/c1 -q c1/classe-250.qry -pm c1.pm -ec c1.ec
./siguel -f c1.geo -o /home/juomzin/Documentos/saidas -e /home/juomzin/Documentos/testes/c1 -q c1/classe-4000.qry -pm c1.pm -ec c1.ec
./siguel -f c1.geo -o /home/juomzin/Documentos/saidas -e /home/juomzin/Documentos/testes/c1 -q c1/classe-5.qry -pm c1.pm -ec c1.ec
./siguel -f c1.geo -o /home/juomzin/Documentos/saidas -e /home/juomzin/Documentos/testes/c1 -q c1/classe-5.qry -pm c1.pm -ec c1.ec
./siguel -f c1.geo -o /home/juomzin/Documentos/saidas -e /home/juomzin/Documentos/testes/c1 -q c1/dados-estabelecimentos.qry -pm c1.pm -ec c1.ec
./siguel -f c1.geo -o /home/juomzin/Documentos/saidas -e /home/juomzin/Documentos/testes/c1 -q c1/dados-morador.qry -pm c1.pm -ec c1.ec
./siguel -f c1.geo -o /home/juomzin/Documentos/saidas -e /home/juomzin/Documentos/testes/c1 -q c1/dq-dumpt-grande.qry -pm c1.pm -ec c1.ec
./siguel -f c1.geo -o /home/juomzin/Documentos/saidas -e /home/juomzin/Documentos/testes/c1 -q c1/dq-dumpt-medio.qry -pm c1.pm -ec c1.ec
./siguel -f c1.geo -o /home/juomzin/Documentos/saidas -e /home/juomzin/Documentos/testes/c1 -q c1/dq-dumpt-pequeno.qry -pm c1.pm -ec c1.ec
./siguel -f c1.geo -o /home/juomzin/Documentos/saidas -e /home/juomzin/Documentos/testes/c1 -q c1/dumptree.qry -pm c1.pm -ec c1.ec
./siguel -f c1.geo -o /home/juomzin/Documentos/saidas -e /home/juomzin/Documentos/testes/c1 -q c1/eplg-1.qry -pm c1.pm -ec c1.ec
./siguel -f c1.geo -o /home/juomzin/Documentos/saidas -e /home/juomzin/Documentos/testes/c1 -q c1/eplg-2.qry -pm c1.pm -ec c1.ec
./siguel -f c1.geo -o /home/juomzin/Documentos/saidas -e /home/juomzin/Documentos/testes/c1 -q c1/eplg-3.qry -pm c1.pm -ec c1.ec
./siguel -f c1.geo -o /home/juomzin/Documentos/saidas -e /home/juomzin/Documentos/testes/c1 -q c1/eplg-4.qry -pm c1.pm -ec c1.ec
./siguel -f c1.geo -o /home/juomzin/Documentos/saidas -e /home/juomzin/Documentos/testes/c1 -q c1/moradores-cep-1.qry -pm c1.pm -ec c1.ec
./siguel -f c1.geo -o /home/juomzin/Documentos/saidas -e /home/juomzin/Documentos/testes/c1 -q c1/moradores-cep-2.qry -pm c1.pm -ec c1.ec
./siguel -f c1.geo -o /home/juomzin/Documentos/saidas -e /home/juomzin/Documentos/testes/c1 -q c1/mudanca-morador.qry -pm c1.pm -ec c1.ec
./siguel -f c1.geo -o /home/juomzin/Documentos/saidas -e /home/juomzin/Documentos/testes/c1 -q c1/mudancas-com-verificacao -pm c1.pm -ec c1.ec
